services:
  mysql:
    image: mysql:9.3
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ~/apps/stavi/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: stavi
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: 'Asia/Taipei'

  redis:
    image: redis:8.2
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ~/apps/stavi/redis/data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}