// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// articleTagsDao is the data access object for the table article_tags.
// You can define custom methods on it to extend its functionality as needed.
type articleTagsDao struct {
	*internal.ArticleTagsDao
}

var (
	// ArticleTags is a globally accessible object for table article_tags operations.
	ArticleTags = articleTagsDao{internal.NewArticleTagsDao()}
)

// Add your custom methods and functionality below.
