// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// cacheDao is the data access object for the table cache.
// You can define custom methods on it to extend its functionality as needed.
type cacheDao struct {
	*internal.CacheDao
}

var (
	// Cache is a globally accessible object for table cache operations.
	Cache = cacheDao{internal.NewCacheDao()}
)

// Add your custom methods and functionality below.
