// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// rolesDao is the data access object for the table roles.
// You can define custom methods on it to extend its functionality as needed.
type rolesDao struct {
	*internal.RolesDao
}

var (
	// Roles is a globally accessible object for table roles operations.
	Roles = rolesDao{internal.NewRolesDao()}
)

// Add your custom methods and functionality below.
